### ISSUE TITLE
初次使用报错404//请继续更新啊，感觉很好用

### ISSUE THREAD

**Issue by mumuxi-git** [Jeric-X/SyncClipboard#11]
请继续更新啊，感觉很好用 @Jeric-X

**Comment by Jeric-X** [comment]
本来是写给自己用的，基本功能能正常使用加上懒癌犯了就好久没更新了，没想到真有其他人会用，感谢支持，要是有什么需求或者问题都可以提，有动力的话说不定可以治愈懒癌

**Comment by mumuxi-git** [comment]
> 本来是写给自己用的，基本功能能正常使用加上懒癌犯了就好久没更新了，没想到真有其他人会用，感谢支持，要是有什么需求或者问题都可以提，有动力的话说不定可以治愈懒癌

你这个思路是挺好的，利用一个中转站可以不受限于局域网。我使用了两个webdav，一个是NAS的，但是有时候抽风，另一个是坚果云的，但总是显示失败如下图。
![](https://mumuxi-pic.oss-cn-guangzhou.aliyuncs.com/img/0dn5ud1d.au0.bmp)
相关的设置如下
![](https://mumuxi-pic.oss-cn-guangzhou.aliyuncs.com/img/xwdnwyqb.tpk.bmp)
在坚果云中新建了clip文件夹，填入账号密码，是不是哪里设置错了，还请帮忙看看。

**Comment by mumuxi-git** [comment]
附上相应的错误日志（使用的坚果云）
[2023/03/25 17:42:11][ProfileFactory.cs   ][ 114] CreateFromRemote failed
[2023/03/25 17:42:11][DownloadService.cs  ][ 139] System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T](Task`1 taskResponse, JsonSerializerOptions options, CancellationToken cancellationToken)
   at SyncClipboard.Service.ProfileFactory.CreateFromRemote(IWebDav webDav, CancellationToken cancelToken) in D:\a\SyncClipboard\SyncClipboard\SyncClipboard\Service\SyncService\Profile\ProfileFactory.cs:line 114
   at SyncClipboard.Service.DownloadService.PullLoop(CancellationToken cancelToken) in D:\a\SyncClipboard\SyncClipboard\SyncClipboard\Service\SyncService\DownloadService.cs:line 156

**Comment by Jeric-X** [comment]
更新了，试试看 https://github.com/Jeric-X/SyncClipboard/releases/tag/v1.3.11，错误原因是程序依赖的文件/文件夹没有被创建，我自己能用是因为我手动创建了
倒不如说之前除了我以外别人根本没法用，有人用才怪嘞🤣

**Comment by mumuxi-git** [comment]
> 更新了，试试看 https://github.com/Jeric-X/SyncClipboard/releases/tag/v1.3.11 错误原因是程序依赖的文件/文件夹没有被创建，我自己能用是因为我手动创建了 倒不如说之前除了我以外别人根本没法用，有人用才怪嘞🤣

感谢，我尝试一下

**Comment by mumuxi-git** [comment]
试了一下，还是使用坚果云的webdav，刚开始的几次还可以，但是大概五次以后就不行了，主要的报错为`Profile Type is Wrong`

附上日志：
[2023/03/25 21:49:02][WebDavClient.cs     ][ 165] Test ok 
[2023/03/25 21:49:02][Global.cs           ][  57] [WebDavClient] test sucess = True
[2023/03/25 21:49:02][ProfileType.cs      ][  29] Profile Type is Wrong
[2023/03/25 21:49:02][DownloadService.cs  ][ 139] System.ArgumentException: Profile Type is Wrong
   at SyncClipboard.Service.ProfileType.StringToClipBoardType(String stringType) in D:\a\SyncClipboard\SyncClipboard\SyncClipboard\Service\SyncService\Profile\ProfileType.cs:line 34
   at SyncClipboard.Service.ProfileFactory.CreateFromRemote(IWebDav webDav, CancellationToken cancelToken) in D:\a\SyncClipboard\SyncClipboard\SyncClipboard\Service\SyncService\Profile\ProfileFactory.cs:line 133
   at SyncClipboard.Service.DownloadService.PullLoop(CancellationToken cancelToken) in D:\a\SyncClipboard\SyncClipboard\SyncClipboard\Service\SyncService\DownloadService.cs:line 156
[2023/03/25 21:49:04][DownloadService.cs  ][ 105][PULL] due to upload service start, cancel
[2023/03/25 21:49:04][ProfileType.cs      ][  29] Profile Type is Wrong
[2023/03/25 21:49:07][ProfileType.cs      ][  29] Profile Type is Wrong
[2023/03/25 21:49:10][ProfileType.cs      ][  29] Profile Type is Wrong
[2023/03/25 21:49:13][DownloadService.cs  ][ 111][PULL] due to upload service stop, cancel
[2023/03/25 21:49:13][ProfileType.cs      ][  29] Profile Type is Wrong
[2023/03/25 21:49:13][DownloadService.cs  ][ 139] System.ArgumentException: Profile Type is Wrong
   at SyncClipboard.Service.ProfileType.StringToClipBoardType(String stringType) in D:\a\SyncClipboard\SyncClipboard\SyncClipboard\Service\SyncService\Profile\ProfileType.cs:line 34
   at SyncClipboard.Service.ProfileFactory.CreateFromRemote(IWebDav webDav, CancellationToken cancelToken) in D:\a\SyncClipboard\SyncClipboard\SyncClipboard\Service\SyncService\Profile\ProfileFactory.cs:line 133
   at SyncClipboard.Service.DownloadService.PullLoop(CancellationToken cancelToken) in D:\a\SyncClipboard\SyncClipboard\SyncClipboard\Service\SyncService\DownloadService.cs:line 156

**Comment by Jeric-X** [comment]
可以附一下网盘里的SyncClipboard.json吗，如果可以的话可以加我qq 295843918 或者邮件联系jericx@jericx.xyz，效率会高一点
