### ISSUE TITLE
[BUG反馈]无限循环下载文件

### ISSUE THREAD

**Issue by Gokou-Ruri** [Jeric-X/SyncClipboard#129]
### 错误描述 | Describe the bug

A客户端复制文本或文件以后，B客户端会无限循环下载此文本内容或文件。

### 复现步骤 | Steps to Reproduce

使用alist挂载本地磁盘作为webdav服务器，alist运行在A设备上，期间所有数据交换行为都处于局域网内。
A、B两台设备均运行相同版本的SyncClipboard（例如v2.8.5），A端复制任何文本或文件，B端未进行任何操作，SyncClipboard会无限循环下载A设备复制的文本或文件，反之亦然。

### 截图 | Screenshots

https://github.com/user-attachments/assets/30e35306-6926-4299-87c6-2c56352dc18d

### 服务端信息 | Server

alist webdav服务端，本地存储模式（非网盘挂载）

### 桌面端信息 | Desktop

Windows 11 23h2 | Synclipboard Version: 2.8.4/2.8.5

### 其他附加信息 | Additional context

A、B设备的log和配置文件：
[SyncClipboard-A.zip](https://github.com/user-attachments/files/17044122/SyncClipboard-A.zip)
[SyncClipboard-B.zip](https://github.com/user-attachments/files/17044124/SyncClipboard-B.zip)

**Comment by Jeric-X** [comment]
这个问题是一直存在吗？还是偶尔发生

可以再使用这里的SyncClipboard.WinUI3再抓一版log吗，我添加了更多的调试信息
https://github.com/Jeric-X/SyncClipboard/actions/runs/10972976447

**Comment by Gokou-Ruri** [comment]
> 这个问题是一直存在吗？还是偶尔发生
> 
> 可以再使用这里的SyncClipboard.WinUI3再抓一版log吗，我添加了更多的调试信息 https://github.com/Jeric-X/SyncClipboard/actions/runs/10972976447

是的，这个问题必定复现。
用debug版本测试了一遍，先清空了两台设备的Windows剪切板，运行SyncClipboard，之后等待一段时间，然后复制文件。
看日志发现即使A设备剪切板为空，A设备复制内容以后，B设备也会疯狂读取捡起恩。，其自己产生的SyncClipboard也会无限复制这个空内容，反之亦然。

**Comment by Jeric-X** [comment]
https://github.com/Jeric-X/SyncClipboard/actions/runs/11125718680
麻烦用这个再抓一次
另外你有使用过别的种类的服务器吗，有没有这个现象

**Comment by Gokou-Ruri** [comment]
> https://github.com/Jeric-X/SyncClipboard/actions/runs/11161725789 麻烦用这个再抓一次 另外你有使用过别的种类的服务器吗，有没有这个现象

这次用的是SyncClipboard的内置服务器，没有用外部webdav服务器。
[SyncClipboard-A.zip](https://github.com/user-attachments/files/17265769/SyncClipboard-A.zip)
[SyncClipboard-B.zip](https://github.com/user-attachments/files/17265770/SyncClipboard-B.zip)

**Comment by Jeric-X** [comment]
> > https://github.com/Jeric-X/SyncClipboard/actions/runs/11161725789 麻烦用这个再抓一次 另外你有使用过别的种类的服务器吗，有没有这个现象
> 
> 这次用的是SyncClipboard的内置服务器，没有用外部webdav服务器。 [SyncClipboard-A.zip](https://github.com/user-attachments/files/17265778/SyncClipboard-A.zip) [SyncClipboard-B.zip](https://github.com/user-attachments/files/17265780/SyncClipboard-B.zip)

这次的log里拷贝的都是文字，没有触发问题吧？
另外更新版本了，Release v2.8.6是最新的

**Comment by baifengs** [comment]
好像我之前了遇到过。因为这几天用的少了，好像没有此问题了。不过我只有一台电脑和一个手机。

**Comment by Gokou-Ruri** [comment]
> > > https://github.com/Jeric-X/SyncClipboard/actions/runs/11161725789 麻烦用这个再抓一次 另外你有使用过别的种类的服务器吗，有没有这个现象
> > 
> > 
> > 这次用的是SyncClipboard的内置服务器，没有用外部webdav服务器。 [SyncClipboard-A.zip](https://github.com/user-attachments/files/17265778/SyncClipboard-A.zip) [SyncClipboard-B.zip](https://github.com/user-attachments/files/17265780/SyncClipboard-B.zip)
> 
> 这次的log里拷贝的都是文字，没有触发问题吧？ 另外更新版本了，Release v2.8.6是最新的

纯文本也会的无限复制的，log里就有。
其实如果这个BUG不好排查的话可以给软件增加一个不重复下载文件或文本的功能，比如文件上传到服务端以后进行hash（或者客户端在上传前对文件进行hash），客户端如果检测到服务端的文件未更新就不继续下载。
或者不hash也行，改成服务端对剪切板的缓存目录进行监测，未监测到文件出现更新或生成新文件（新上传），就不向客户端声明文件已更新，这样客户端认为文件未更新，就不会重复下载同一个文件或文本了。

甚至衍生一下，这个功能除了防止重复下载以外，还能防止重复上传。例如客户端在上传前对文件或文本进行hash能防止多端上传重复内容，反正hash小文件或文本内容的速度非常快，基本是毫秒级，在剪切板同步这个使用场景中也不会对性能和响应速度产生什么负担。

**Comment by Jeric-X** [comment]
文件上传下载前都有提前检查hash的
我看你同步后通知也是关的，文字无限下载你是怎么看出来的？

**Comment by Gokou-Ruri** [comment]
> 文件上传下载前都有提前检查hash的 我看你同步后通知也是关的，文字无限下载你是怎么看出来的？

https://github.com/Jeric-X/SyncClipboard/issues/129#issuecomment-2395007437
这里面有无限下载文本内容的log。
另外，即使是空剪切板也会无限下载（因为之前有几次测试前我试过清空过剪切板），之前的log里也有的，所以和剪切板里的内容没什么关系。

**Comment by Jeric-X** [comment]
我想你说的是轮询检查服务端剪贴板内容的产生的log，这个软件当前的原理就是不断轮询服务器。文件的话会每次只下载hash值，文字的话确实会完整下载文字内容，这点不是bug。将这条issue打上bug标签的原因是1L视频里中的内容：文件下载失败无限弹窗系统通知

**Comment by Gokou-Ruri** [comment]
> 我想你说的是轮询检查服务端剪贴板内容的产生的log，这个软件当前的原理就是不断轮询服务器。文件的话会每次只下载hash值，文字的话确实会完整下载文字内容，这点不是bug。将这条issue打上bug标签的原因是1L视频里中的内容：文件下载失败无限弹窗系统通知

视频里不是下载失败，是无限下载。网速和磁盘读写都在持续波动，关掉SyncClipboard就无网速和磁盘读写波动了。

**Comment by rockingdice** [comment]
我好像遇到类似的问题了，症状是我用vscode复制一段代码，然后再粘贴的时候，本来4行的字符串粘贴出了好几万行，而且撤销以后再粘贴又变成20几万行（多出来的全是空行），而且有的时候粘贴也很奇怪，可能会在每一行代码中间穿插若干行空行（而不只是在剪贴板的末尾）。
复制文件的时候也会有类似的问题，因为我都开了同步剪贴板的通知，偶尔会遇到复制一个文件，另一边电脑疯狂弹通知，必须再去复制一下别的东西才能停止。

我的环境是win+mac都在内网，win是服务器，mac是客户端连win，打开了同步剪贴板。

有没有可能，是因为互相触发了剪贴板变更，才导致的无限循环？
A复制 剪贴板变更
B收到 变更剪贴板 
然后B又通知A变更……

不过这解释不了我遇到的那个往复制文字中间穿插空行的行为。

没看代码，瞎猜一下：有没有异步处理？io、网络延迟等都可能会引起非同步操作的错误逻辑，这个问题看来是延迟（时间）敏感的。

**Comment by Jeric-X** [comment]
@rockingdice 
1. 有许多异步相关的加减锁操作，代码十分复杂也很脆弱，所以我也很希望用户能够帮忙找到较为稳定的复现方法，或者在触发问题时第一时间上传log
2. 插入空行这个问题我倒是没见过，不知是否容易复现

**Comment by rockingdice** [comment]
> [@rockingdice](https://github.com/rockingdice)
> 
> 1. 有许多异步相关的加减锁操作，代码十分复杂也很脆弱，所以我也很希望用户能够帮忙找到较为稳定的复现方法，或者在触发问题时第一时间上传log
> 2. 插入空行这个问题我倒是没见过，不知是否容易复现

日志（小心：解压后500mb）：

[20250225 - 副本.zip](https://github.com/user-attachments/files/18959703/20250225.-.zip)

可以看出这个应该是某种不断重试的过程，然后每次重试都会新增空行，不断重试空行越来越多，因为每次都会输出完整的日志，所以日志也会迅速膨胀。
文件那个我猜大概也与重试有关系吧，那个不常见。
我这是必现的，关了再开也不行。可惜没太多时间要不就debug一下了（

**Comment by rockingdice** [comment]
![Image](https://github.com/user-attachments/assets/286a216b-df61-4337-a871-4787f3488656)

调用的这里，疯狂调用，复制一下就能出好几十兆的日志。线程某种情况下会堆积？

```
[2025/02/25 16:10:00][ClipboardChangingListenerBase.cs][  86] Clipboard handler unhandled exception Insufficient memory to continue the execution of the program.
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|38_0(Int32 hr)
   at ABI.Windows.ApplicationModel.DataTransfer.IDataPackageViewMethods.get_AvailableFormats(IObjectReference _obj)
   at SyncClipboard.WinUI3.ClipboardWinUI.ClipboardFactory.GetMetaInfomationCurrentThread(CancellationToken ctk) in D:\a\SyncClipboard\SyncClipboard\src\SyncClipboard.WinUI3\ClipboardWinUI\ClipboardFactory.cs:line 148
   at SyncClipboard.Core.Clipboard.ClipboardChangingListenerBase.<get_NotifyAll>b__22_0(ClipboardMetaInfomation meta) in D:\a\SyncClipboard\SyncClipboard\src\SyncClipboard.Core\Clipboard\ClipboardChangingListenerBase.cs:line 94
```

日志里找到的

**Comment by Jeric-X** [comment]
@rockingdice 
惊人的压缩率（）
看了你的log，我怀疑可能是代码结尾的\r\n在某些转换的过程中变成了两次换行，但又变成了两个\r\n，（这可能是与synergy冲突导致的），进入死循环导致无数个换行，然后内存不足进而引起连锁反应
确认是与synergy同时使用时，并且编辑器是vscode，才有这个问题吗

**Comment by rockingdice** [comment]
synergy应该是有关系的，而且它也会复制文件，估计是那个新的空行引起的剪贴板一直在变化，然后就无限循环了。
我觉得要么就做个delay，y秒之内的剪贴板变化只处理一次，一般人用的话没那么敏感，但是对进程来说就能爆炸了。
但是对我来说只用一边就解决问题了…

**Comment by charklaliu** [comment]
我使用微信输入法的跨平台剪贴板也有类似的问题。然后只能删除微信输入法了
