### ISSUE TITLE
v2.8.6 無法複製文字

### ISSUE THREAD

**Issue by ACh-K** [Jeric-X/SyncClipboard#135]
### 错误描述 | Describe the bug

~~好久不見 ww~~

將 Windows 和 macOS 的 SyncClipboard 更新到最新版本之後，發現無法在兩台電腦間複製文字，然而檔案和圖片的複製功能依然正常。

將 Windows 的 SyncClipboard 版本降回 v2.8.5 後，文字複製功能恢復正常，因此推測問題可能出在伺服器端的 SyncClipboard。

### 复现步骤 | Steps to Reproduce

複製一段文字並嘗試在另一台電腦貼上。

### 服务端信息 | Server

同個網路的環境下透過 IP 直接連線（不確定是屬於哪種）

### 桌面端信息 | Desktop

Windows 11 23H2, SyncClipboard Version: v2.8.6

### 移动端信息 | Smartphone

macOS Sequoia 15.0.1, SyncClipboard Version: v0.7.7

### 其他附加信息 | Additional context

複製文字之後產生的 log：

- Windows

  ```
  [2024/10/08 23:33:38][ClipboardFactory.cs ][ 172][ClipboardFactory] System.Runtime.InteropServices.COMException (0x8001010E): 應用程式所呼叫了整理給不同執行緒的介面。
  
  DataPackage 不包含指定的格式。請使用 DataPackageView.Contains 或 DataPackageView.AvailableFormats 驗證其狀態。
     at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
     at ABI.Windows.ApplicationModel.DataTransfer.IDataPackageViewMethods.GetBitmapAsync(IObjectReference _obj)
     at Windows.ApplicationModel.DataTransfer.DataPackageView.GetBitmapAsync()
     at SyncClipboard.WinUI3.ClipboardWinUI.ClipboardFactory.HanleBitmap(DataPackageView ClipboardData, ClipboardMetaInfomation meta, CancellationToken ctk) in D:\a\SyncClipboard\SyncClipboard\src\SyncClipboard.WinUI3\ClipboardWinUI\ClipboardFactory.cs:line 55
     at SyncClipboard.WinUI3.ClipboardWinUI.ClipboardFactory.GetMetaInfomation(CancellationToken ctk) in D:\a\SyncClipboard\SyncClipboard\src\SyncClipboard.WinUI3\ClipboardWinUI\ClipboardFactory.cs:line 166
  ```

- macOS

  ```
  [2024/10/08 23:33:38][                    ][   0][ClipboardFactoryBase] ClipboardProfileDTO { File = , Clipboard = , Type = Unknown }
  [2024/10/08 23:33:38][                    ][   0][PULL] remote is {"File":"","Clipboard":"","Type":"Unknown"}
  ```

**Comment by Baiyssy** [comment]
我也碰到了同样的问题。

**Comment by ACh-K** [comment]
後來發現 macOS 用戶端 v0.7.7 似乎和 Windows 伺服器端 v2.8.5 不相容。

在伺服器端複製檔案或圖片後，將無法從用戶端複製檔案或圖片到伺服器端，必須複製文字之後才會恢復正常。
