### ISSUE TITLE
win11上经常崩溃

### ISSUE THREAD

**Issue by SGAOCR** [Jeric-X/SyncClipboard#35]
```
OS Name: Microsoft Windows 11 Pro for Workstations
Version: 10.0.22621 Build 22621
```

[2024/01/25 23:43:45][ClipboardFactoryBase.cs][  64][ClipboardFactoryBase] ClipboardProfileDTO { File = , Clipboard = aaa, Type = Text }

[2024/01/25 23:43:45][DownloadService.cs  ][ 176][PULL] remote is {"File":"","Clipboard":"aaa","Type":"Text"}

[2024/01/25 23:43:46][App.xaml.cs         ][  60] UnhandledException System.OutOfMemoryException Insufficient memory to continue the execution of the program. 
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.DataTransfer.IDataPackageViewMethods.get_AvailableFormats(IObjectReference _obj)
   at SyncClipboard.WinUI3.ClipboardWinUI.ClipboardFactory.GetMetaInfomation(CancellationToken ctk) in D:\a\SyncClipboard\SyncClipboard\src\SyncClipboard.WinUI3\ClipboardWinUI\ClipboardFactory.cs:line 91
   at SyncClipboard.WinUI3.ClipboardWinUI.ClipboardListener.HandleClipboardChanged(Object _, Object _1) in D:\a\SyncClipboard\SyncClipboard\src\SyncClipboard.WinUI3\ClipboardWinUI\ClipboardListener.cs:line 34
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()

[2024/01/25 23:43:50][ClipboardHander.cs  ][  52][EASY IMAGE] Service: Image Assistant stopped
[2024/01/25 23:43:50][ClipboardHander.cs  ][  52][COMPATIBILITY] Service: Image Compatibility stopped
[2024/01/25 23:43:50][ClipboardHander.cs  ][  52][PUSH] Service: Clipboard Syncing stopped

怀疑是微软的这个api bug造成的
https://github.com/microsoft/microsoft-ui-xaml/issues/6754

**Comment by Jeric-X** [comment]
是的，最近我也发现了这个问题，一直在着手搞这个，看起来你用的版本也是主线上还未发布的版本，这个版本在crash时应该会创建dump，在log目录的父文件夹里(日期 时间.dmp)，不知道你能否上传上来
>  [2024/01/25 23:43:46][App.xaml.cs ][ 60] UnhandledException System.OutOfMemoryException Insufficient memory to continue the execution of the program.

看log是发生了OOM，和微软的这个问题好像不太一样

**Comment by Jeric-X** [comment]
软件可能涉及的个人信息有：服务器配置信息（地址，用户名，密码），当时剪切板内储存的信息，不会获取其他个人信息
当前dump的设定是最小dump，应该只包含寄存器/调用堆栈之类的基础信息的，不会dump整个内存，应该没有上边的信息，但是我也不敢完全肯定
不算剪切板内信息(看log之前是`aaa`，之后获取失败异常退出)，如果你的服务器信息不怕泄露(局域网部署/可以改密码等)，可以直接在这里上传，如果希望信息限制在最小范围，可以单独给我发邮件

**Comment by SGAOCR** [comment]
目前在公司的电脑上使用，涉及公司的一些数据，不让分享。后面如果在个人电脑上crash，可以给你发email。

**Comment by Jeric-X** [comment]
现在的主线最新的代码应该没有那么容易异常退出了，是我前几天的修改导致了任何小问题都会使整个软件退出，还没有影响到Release中的版本
现在遇到OutOfMemory异常只会生成dump，不会直接退出，我认为这是系统内存紧张时的正常现象，如果你观测到SyncClipboard在任务管理器中有大量异常内存占用(正常是200MB以下)，还是可以发送给我dump文件
使用测试版软件是这样的啦👌
