### ISSUE TITLE
启动时崩溃

### ISSUE THREAD

**Issue by yunkuangao** [Jeric-X/SyncClipboard#46]
OS: windows 11

已安装相关依赖,启动直接闪退

日志

```
[2024/03/05 06:00:37][App.xaml.cs         ][  92] App started
[2024/03/05 06:00:37][WebDavBase.cs       ][ 193] [WebDAV] Test WebDav Failed, message = An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.
[2024/03/05 06:00:37][ClipboardHander.cs  ][  23][EASY IMAGE] Service: 图片轻松拷贝 started
[2024/03/05 06:00:37][ClipboardHander.cs  ][  23][COMPATIBILITY] Service: 图片兼容性优化 started
[2024/03/05 06:00:37][ClipboardHander.cs  ][  23][PUSH] Service: 剪贴板同步 started
[2024/03/05 06:00:37][App.xaml.cs         ][  64] UnhandledException System.Runtime.InteropServices.COMException 函数不正确。 (0x80070001) 
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at H.NotifyIcon.Interop.InteropUtilities.EnsureNonZero(BOOL value) in /_/src/libs/H.NotifyIcon/Interop/InteropUtilities.cs:line 85
   at H.NotifyIcon.EfficiencyMode.EfficiencyModeUtilities.SetProcessQualityOfServiceLevel(QualityOfServiceLevel level) in /_/src/libs/H.NotifyIcon/EfficiencyMode/EfficiencyModeUtilities.cs:line 53
   at H.NotifyIcon.EfficiencyMode.EfficiencyModeUtilities.SetEfficiencyMode(Boolean value) in /_/src/libs/H.NotifyIcon/EfficiencyMode/EfficiencyModeUtilities.cs:line 97
   at H.NotifyIcon.TaskbarIcon.ForceCreate(Boolean enablesEfficiencyMode) in /_/src/libs/H.NotifyIcon.Shared/TaskbarIcon.cs:line 135
   at SyncClipboard.WinUI3.Views.TrayIconImpl.Create() in D:\a\SyncClipboard\SyncClipboard\src\SyncClipboard.WinUI3\Views\TrayIconImpl.cs:line 38
   at SyncClipboard.Core.AppCore.InitTrayIcon() in D:\a\SyncClipboard\SyncClipboard\src\SyncClipboard.Core\AppCore.cs:line 93
   at SyncClipboard.Core.AppCore.Run() in D:\a\SyncClipboard\SyncClipboard\src\SyncClipboard.Core\AppCore.cs:line 58
   at SyncClipboard.WinUI3.App.OnLaunched(LaunchActivatedEventArgs args) in D:\a\SyncClipboard\SyncClipboard\src\SyncClipboard.WinUI3\App.xaml.cs:line 93
   at Microsoft.UI.Xaml.Application.Microsoft.UI.Xaml.IApplicationOverrides.OnLaunched(LaunchActivatedEventArgs args)
   at ABI.Microsoft.UI.Xaml.IApplicationOverrides.Do_Abi_OnLaunched_0(IntPtr thisPtr, IntPtr args)
[2024/03/05 06:00:56][App.xaml.cs         ][  92] App started
[2024/03/05 06:00:56][WebDavBase.cs       ][ 193] [WebDAV] Test WebDav Failed, message = An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.
[2024/03/05 06:00:56][ClipboardHander.cs  ][  23][EASY IMAGE] Service: 图片轻松拷贝 started
[2024/03/05 06:00:56][ClipboardHander.cs  ][  23][COMPATIBILITY] Service: 图片兼容性优化 started
[2024/03/05 06:00:56][ClipboardHander.cs  ][  23][PUSH] Service: 剪贴板同步 started
[2024/03/05 06:00:56][App.xaml.cs         ][  64] UnhandledException System.Runtime.InteropServices.COMException 函数不正确。 (0x80070001) 
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at H.NotifyIcon.Interop.InteropUtilities.EnsureNonZero(BOOL value) in /_/src/libs/H.NotifyIcon/Interop/InteropUtilities.cs:line 85
   at H.NotifyIcon.EfficiencyMode.EfficiencyModeUtilities.SetProcessQualityOfServiceLevel(QualityOfServiceLevel level) in /_/src/libs/H.NotifyIcon/EfficiencyMode/EfficiencyModeUtilities.cs:line 53
   at H.NotifyIcon.EfficiencyMode.EfficiencyModeUtilities.SetEfficiencyMode(Boolean value) in /_/src/libs/H.NotifyIcon/EfficiencyMode/EfficiencyModeUtilities.cs:line 97
   at H.NotifyIcon.TaskbarIcon.ForceCreate(Boolean enablesEfficiencyMode) in /_/src/libs/H.NotifyIcon.Shared/TaskbarIcon.cs:line 135
   at SyncClipboard.WinUI3.Views.TrayIconImpl.Create() in D:\a\SyncClipboard\SyncClipboard\src\SyncClipboard.WinUI3\Views\TrayIconImpl.cs:line 38
   at SyncClipboard.Core.AppCore.InitTrayIcon() in D:\a\SyncClipboard\SyncClipboard\src\SyncClipboard.Core\AppCore.cs:line 93
   at SyncClipboard.Core.AppCore.Run() in D:\a\SyncClipboard\SyncClipboard\src\SyncClipboard.Core\AppCore.cs:line 58
   at SyncClipboard.WinUI3.App.OnLaunched(LaunchActivatedEventArgs args) in D:\a\SyncClipboard\SyncClipboard\src\SyncClipboard.WinUI3\App.xaml.cs:line 93
   at Microsoft.UI.Xaml.Application.Microsoft.UI.Xaml.IApplicationOverrides.OnLaunched(LaunchActivatedEventArgs args)
   at ABI.Microsoft.UI.Xaml.IApplicationOverrides.Do_Abi_OnLaunched_0(IntPtr thisPtr, IntPtr args)
[2024/03/05 06:02:08][App.xaml.cs         ][  92] App started
[2024/03/05 06:02:08][WebDavBase.cs       ][ 193] [WebDAV] Test WebDav Failed, message = An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.
[2024/03/05 06:02:08][ClipboardHander.cs  ][  23][EASY IMAGE] Service: 图片轻松拷贝 started
[2024/03/05 06:02:09][ClipboardHander.cs  ][  23][COMPATIBILITY] Service: 图片兼容性优化 started
[2024/03/05 06:02:09][ClipboardHander.cs  ][  23][PUSH] Service: 剪贴板同步 started
[2024/03/05 06:02:09][App.xaml.cs         ][  64] UnhandledException System.Runtime.InteropServices.COMException 函数不正确。 (0x80070001) 
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at H.NotifyIcon.Interop.InteropUtilities.EnsureNonZero(BOOL value) in /_/src/libs/H.NotifyIcon/Interop/InteropUtilities.cs:line 85
   at H.NotifyIcon.EfficiencyMode.EfficiencyModeUtilities.SetProcessQualityOfServiceLevel(QualityOfServiceLevel level) in /_/src/libs/H.NotifyIcon/EfficiencyMode/EfficiencyModeUtilities.cs:line 53
   at H.NotifyIcon.EfficiencyMode.EfficiencyModeUtilities.SetEfficiencyMode(Boolean value) in /_/src/libs/H.NotifyIcon/EfficiencyMode/EfficiencyModeUtilities.cs:line 97
   at H.NotifyIcon.TaskbarIcon.ForceCreate(Boolean enablesEfficiencyMode) in /_/src/libs/H.NotifyIcon.Shared/TaskbarIcon.cs:line 135
   at SyncClipboard.WinUI3.Views.TrayIconImpl.Create() in D:\a\SyncClipboard\SyncClipboard\src\SyncClipboard.WinUI3\Views\TrayIconImpl.cs:line 38
   at SyncClipboard.Core.AppCore.InitTrayIcon() in D:\a\SyncClipboard\SyncClipboard\src\SyncClipboard.Core\AppCore.cs:line 93
   at SyncClipboard.Core.AppCore.Run() in D:\a\SyncClipboard\SyncClipboard\src\SyncClipboard.Core\AppCore.cs:line 58
   at SyncClipboard.WinUI3.App.OnLaunched(LaunchActivatedEventArgs args) in D:\a\SyncClipboard\SyncClipboard\src\SyncClipboard.WinUI3\App.xaml.cs:line 93
   at Microsoft.UI.Xaml.Application.Microsoft.UI.Xaml.IApplicationOverrides.OnLaunched(LaunchActivatedEventArgs args)
   at ABI.Microsoft.UI.Xaml.IApplicationOverrides.Do_Abi_OnLaunched_0(IntPtr thisPtr, IntPtr args)
[2024/03/05 06:02:10][App.xaml.cs         ][  92] App started
[2024/03/05 06:02:10][WebDavBase.cs       ][ 193] [WebDAV] Test WebDav Failed, message = An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.
[2024/03/05 06:02:10][ClipboardHander.cs  ][  23][EASY IMAGE] Service: 图片轻松拷贝 started
[2024/03/05 06:02:10][ClipboardHander.cs  ][  23][COMPATIBILITY] Service: 图片兼容性优化 started
[2024/03/05 06:02:10][ClipboardHander.cs  ][  23][PUSH] Service: 剪贴板同步 started
[2024/03/05 06:02:10][App.xaml.cs         ][  64] UnhandledException System.Runtime.InteropServices.COMException 函数不正确。 (0x80070001) 
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at H.NotifyIcon.Interop.InteropUtilities.EnsureNonZero(BOOL value) in /_/src/libs/H.NotifyIcon/Interop/InteropUtilities.cs:line 85
   at H.NotifyIcon.EfficiencyMode.EfficiencyModeUtilities.SetProcessQualityOfServiceLevel(QualityOfServiceLevel level) in /_/src/libs/H.NotifyIcon/EfficiencyMode/EfficiencyModeUtilities.cs:line 53
   at H.NotifyIcon.EfficiencyMode.EfficiencyModeUtilities.SetEfficiencyMode(Boolean value) in /_/src/libs/H.NotifyIcon/EfficiencyMode/EfficiencyModeUtilities.cs:line 97
   at H.NotifyIcon.TaskbarIcon.ForceCreate(Boolean enablesEfficiencyMode) in /_/src/libs/H.NotifyIcon.Shared/TaskbarIcon.cs:line 135
   at SyncClipboard.WinUI3.Views.TrayIconImpl.Create() in D:\a\SyncClipboard\SyncClipboard\src\SyncClipboard.WinUI3\Views\TrayIconImpl.cs:line 38
   at SyncClipboard.Core.AppCore.InitTrayIcon() in D:\a\SyncClipboard\SyncClipboard\src\SyncClipboard.Core\AppCore.cs:line 93
   at SyncClipboard.Core.AppCore.Run() in D:\a\SyncClipboard\SyncClipboard\src\SyncClipboard.Core\AppCore.cs:line 58
   at SyncClipboard.WinUI3.App.OnLaunched(LaunchActivatedEventArgs args) in D:\a\SyncClipboard\SyncClipboard\src\SyncClipboard.WinUI3\App.xaml.cs:line 93
   at Microsoft.UI.Xaml.Application.Microsoft.UI.Xaml.IApplicationOverrides.OnLaunched(LaunchActivatedEventArgs args)
   at ABI.Microsoft.UI.Xaml.IApplicationOverrides.Do_Abi_OnLaunched_0(IntPtr thisPtr, IntPtr args)
[2024/03/05 06:02:20][App.xaml.cs         ][  92] App started
[2024/03/05 06:02:20][WebDavBase.cs       ][ 193] [WebDAV] Test WebDav Failed, message = An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.
[2024/03/05 06:02:20][ClipboardHander.cs  ][  23][EASY IMAGE] Service: 图片轻松拷贝 started
[2024/03/05 06:02:20][ClipboardHander.cs  ][  23][COMPATIBILITY] Service: 图片兼容性优化 started
[2024/03/05 06:02:20][ClipboardHander.cs  ][  23][PUSH] Service: 剪贴板同步 started
[2024/03/05 06:02:20][App.xaml.cs         ][  64] UnhandledException System.Runtime.InteropServices.COMException 函数不正确。 (0x80070001) 
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at H.NotifyIcon.Interop.InteropUtilities.EnsureNonZero(BOOL value) in /_/src/libs/H.NotifyIcon/Interop/InteropUtilities.cs:line 85
   at H.NotifyIcon.EfficiencyMode.EfficiencyModeUtilities.SetProcessQualityOfServiceLevel(QualityOfServiceLevel level) in /_/src/libs/H.NotifyIcon/EfficiencyMode/EfficiencyModeUtilities.cs:line 53
   at H.NotifyIcon.EfficiencyMode.EfficiencyModeUtilities.SetEfficiencyMode(Boolean value) in /_/src/libs/H.NotifyIcon/EfficiencyMode/EfficiencyModeUtilities.cs:line 97
   at H.NotifyIcon.TaskbarIcon.ForceCreate(Boolean enablesEfficiencyMode) in /_/src/libs/H.NotifyIcon.Shared/TaskbarIcon.cs:line 135
   at SyncClipboard.WinUI3.Views.TrayIconImpl.Create() in D:\a\SyncClipboard\SyncClipboard\src\SyncClipboard.WinUI3\Views\TrayIconImpl.cs:line 38
   at SyncClipboard.Core.AppCore.InitTrayIcon() in D:\a\SyncClipboard\SyncClipboard\src\SyncClipboard.Core\AppCore.cs:line 93
   at SyncClipboard.Core.AppCore.Run() in D:\a\SyncClipboard\SyncClipboard\src\SyncClipboard.Core\AppCore.cs:line 58
   at SyncClipboard.WinUI3.App.OnLaunched(LaunchActivatedEventArgs args) in D:\a\SyncClipboard\SyncClipboard\src\SyncClipboard.WinUI3\App.xaml.cs:line 93
   at Microsoft.UI.Xaml.Application.Microsoft.UI.Xaml.IApplicationOverrides.OnLaunched(LaunchActivatedEventArgs args)
   at ABI.Microsoft.UI.Xaml.IApplicationOverrides.Do_Abi_OnLaunched_0(IntPtr thisPtr, IntPtr args)
[2024/03/05 06:02:22][App.xaml.cs         ][  92] App started
[2024/03/05 06:02:23][WebDavBase.cs       ][ 193] [WebDAV] Test WebDav Failed, message = An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.
[2024/03/05 06:02:23][ClipboardHander.cs  ][  23][EASY IMAGE] Service: 图片轻松拷贝 started
[2024/03/05 06:02:23][ClipboardHander.cs  ][  23][COMPATIBILITY] Service: 图片兼容性优化 started
[2024/03/05 06:02:23][ClipboardHander.cs  ][  23][PUSH] Service: 剪贴板同步 started
[2024/03/05 06:02:23][App.xaml.cs         ][  64] UnhandledException System.Runtime.InteropServices.COMException 函数不正确。 (0x80070001) 
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at H.NotifyIcon.Interop.InteropUtilities.EnsureNonZero(BOOL value) in /_/src/libs/H.NotifyIcon/Interop/InteropUtilities.cs:line 85
   at H.NotifyIcon.EfficiencyMode.EfficiencyModeUtilities.SetProcessQualityOfServiceLevel(QualityOfServiceLevel level) in /_/src/libs/H.NotifyIcon/EfficiencyMode/EfficiencyModeUtilities.cs:line 53
   at H.NotifyIcon.EfficiencyMode.EfficiencyModeUtilities.SetEfficiencyMode(Boolean value) in /_/src/libs/H.NotifyIcon/EfficiencyMode/EfficiencyModeUtilities.cs:line 97
   at H.NotifyIcon.TaskbarIcon.ForceCreate(Boolean enablesEfficiencyMode) in /_/src/libs/H.NotifyIcon.Shared/TaskbarIcon.cs:line 135
   at SyncClipboard.WinUI3.Views.TrayIconImpl.Create() in D:\a\SyncClipboard\SyncClipboard\src\SyncClipboard.WinUI3\Views\TrayIconImpl.cs:line 38
   at SyncClipboard.Core.AppCore.InitTrayIcon() in D:\a\SyncClipboard\SyncClipboard\src\SyncClipboard.Core\AppCore.cs:line 93
   at SyncClipboard.Core.AppCore.Run() in D:\a\SyncClipboard\SyncClipboard\src\SyncClipboard.Core\AppCore.cs:line 58
   at SyncClipboard.WinUI3.App.OnLaunched(LaunchActivatedEventArgs args) in D:\a\SyncClipboard\SyncClipboard\src\SyncClipboard.WinUI3\App.xaml.cs:line 93
   at Microsoft.UI.Xaml.Application.Microsoft.UI.Xaml.IApplicationOverrides.OnLaunched(LaunchActivatedEventArgs args)
   at ABI.Microsoft.UI.Xaml.IApplicationOverrides.Do_Abi_OnLaunched_0(IntPtr thisPtr, IntPtr args)

```

dmp:
[2024-03-05 06-02-23.dmp](https://github.com/Jeric-X/SyncClipboard/files/14487716/2024-03-05.06-02-23.dmp)

**Comment by Jeric-X** [comment]
https://github.com/Jeric-X/SyncClipboard/actions/runs/8151682586
可以测试一下这个版本吗

**Comment by yunkuangao** [comment]
可以了，感谢
