### ISSUE TITLE
同時複製多份檔案／複製資料夾

### ISSUE THREAD

**Issue by ACh-K** [Jeric-X/SyncClipboard#69]
在 Windows 11、macOS 14（無論哪一方作為 server 或 client）的環境下測試發現：
- 若選取多份檔案進行複製，在另一端只能貼上選取的檔案中處於最開頭的檔案
- 在 Windows 端對資料夾（無論裡面有無檔案）進行複製，在 macOS 端會跳出這個通知並顯示以下的 log
  <img width="370" alt="ghrt14wl n2r" src="https://github.com/Jeric-X/SyncClipboard/assets/98224334/f529750c-70a6-41ff-ad29-9bdebef8150c">
- ```
  [2024/05/04 03:38:28][                    ][   0][ClipboardFactoryBase] ClipboardProfileDTO { File = , Clipboard = , Type = Unknown }
  [2024/05/04 03:38:28][                    ][   0][PULL] remote is {"File":"","Clipboard":"","Type":"Unknown"}
  [2024/05/04 03:38:28][                    ][   0] _isChangingLocal set to TRUE
  [2024/05/04 03:38:28][                    ][   0] _isChangingLocal set to FALSE
  [2024/05/04 03:38:28][DownloadService.cs  ][ 270] System.NotImplementedException: Arg_NotImplementedException
     at SyncClipboard.Core.Clipboard.UnkonwnProfile.get_ClipboardSetter() in /Users/runner/work/SyncClipboard.Desktop/SyncClipboard.Desktop/src/SyncClipboard.Core/Clipboard/Profile/UnkonwnProfile.cs:line 11
     at SyncClipboard.Core.Clipboard.Profile.SetLocalClipboard(Boolean notify, CancellationToken ctk) in /Users/runner/work/SyncClipboard.Desktop/SyncClipboard.Desktop/src/SyncClipboard.Core/Clipboard/Profile/Profile.cs:line 63
     at SyncClipboard.Core.UserServices.DownloadService.SetRemoteProfileToLocal(Profile remoteProfile, CancellationToken cancelToken) in /Users/runner/work/SyncClipboard.Desktop/SyncClipboard.Desktop/src/SyncClipboard.Core/UserServices/SyncService/DownloadService.cs:line 347
     at SyncClipboard.Core.UserServices.DownloadService.DownloadProcess(CancellationToken token) in /Users/runner/work/SyncClipboard.Desktop/SyncClipboard.Desktop/src/SyncClipboard.Core/UserServices/SyncService/DownloadService.cs:line 302
     at SyncClipboard.Core.UserServices.DownloadService.PullLoop(CancellationToken cancelToken) in /Users/runner/work/SyncClipboard.Desktop/SyncClipboard.Desktop/src/SyncClipboard.Core/UserServices/SyncService/DownloadService.cs:line 270
  ```
- 在 macOS 端對資料夾（無論裡面有無檔案）進行複製的話，只能複製檔名到 Windows 端
  <img width="316" alt="image" src="https://github.com/Jeric-X/SyncClipboard/assets/98224334/9acee87e-9f7d-4152-96da-39d7600c8713">
  ```
  [2024/05/04 04:12:53][ClipboardFactory.cs ][ 153][ClipboardFactory] Text: 總之是資料夾
  SyncClipboard_0.6.4_macos_x64.dmg
  SyncClipboard_0.6.4_macos_arm64.dmg
  ```

**Comment by Jeric-X** [comment]
多个文件和文件夹目前是不支持的，会在未来支持
通知中的报错会尽快修复
